spring:
  application:
    name: ys-service-sso
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/huanjv?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.lovecyy.sso.common.dto
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    #驼峰式命名
    map-underscore-to-camel-case: true